# -*- coding: utf-8 -*-
"""Processing2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xyfvNZOWLvBfRpj4ZljfrXbulsyMTxR
"""

#Adelaide Call
# 3/8/24
#1. Built in functions are functions that are already in the programming language. A programmer defined function is a function that is written by the programmer.
#2. Void functions are functions that terminates after preforming a specific task. A value function is a function that takes in acts on and returns values.

#Problem 1
lst = [23, 56, 19, 52, 87, 88, 50, 34, 22, 61, 52, 43, 25, 76, 77, 94]
print("Total numbers in list:",len(lst))
print("Max value in list:",max(lst))
print("Min value in list:",min(lst))
print("Combined total:",sum(lst))

#Problem 2
def name_print(first, last):
  print(first, last)
  print(last, ",", first)
  print(first.upper(), last.upper())
  spaced = ""
  for letter in first:
    spaced = spaced + letter + " "
  for letter in last:
    spaced = spaced + letter + " "
  print(spaced)
first_name = input("Enter first name: ")
last_name = input("Enter last name: ")

name_print(first_name, last_name)

#Problem 3
import random
def dice_roll():
  return random.randint(1,6)
die = dice_roll()
print(die)
print("Try to guess the die roll!")
guess = ""
guesses = 0
while guesses < 3 :
  guess = input("Guess a number from 1-6:")
  guess = int(guess)
  guesses += 1
  if guess != die and guesses < 3 :
   print ("Incorrect try again.")
  if guesses == 3:
    print("You Lose.")
    break
  if guess == die :
    print("You did it!")
    break